### PR TITLE
Need help!

### PR DESCRIPTION
**Pull request by NicolasAsis**
I cannot see the text for the TextInput. Need help.

### CODE REVIEW

**Review by dddora — COMMENTED** [review]
I think you miss the "placeholder"?

**Comment by DeriqDanois** [comment]
Try finding a function that will allocate the textinput value/display to your current state

**Comment by DeriqDanois** [comment]
import React, { Component } from 'react';
import { View, TextInput } from 'react-native';

function UselessTextInput(props) {
  return (
    <TextInput
      {...props} // Inherit any props passed to it; e.g., multiline, numberOfLines below
      editable
      maxLength={40}
    />
  );
}

export default function UselessTextInputMultiline() {
  const [value, onChangeText] = React.useState('Useless Multiline Placeholder');

  // If you type something in the text box that is a color, the background will change to that
  // color.
  return (
    <View
      style={{
        backgroundColor: value,
        borderBottomColor: '#000000',
        borderBottomWidth: 1,
      }}>
      <UselessTextInput
        multiline
        numberOfLines={4}
        onChangeText={text => onChangeText(text)}
        value={value}
      />
    </View>
  );
}

**Comment by DeriqDanois** [comment]
https://facebook.github.io/react-native/docs/textinput

**Review by nicoleli11 — COMMENTED** [review]
is it because React.useState?

**Comment by DeriqDanois** [comment]
<Textinput>{state}<Textinput>

**Comment by DeriqDanois** [comment]
< Textinput >{text}< Textinput />

**Comment by DeriqDanois** [comment]
< Textinput 
function 
style
>{value}</Textinput>

**Comment by DeriqDanois** [comment]
< Textinput
function
style
>{value}<Textinput>

**Comment by DeriqDanois** [comment]
<Textinput
function={}
style={{}}
>{value}<Textinpt>

**Comment by DeriqDanois** [comment]
<TextInput placeholder="value"

**Comment by DeriqDanois** [comment]
<TextInput placeholderText

**Comment by DeriqDanois** [comment]
https://facebook.github.io/react-native/docs/textinput
Command f placeholder

**Comment by NicolasAsis** [comment]
I figured it out...needed to change the height of the TextInput...

**Review by nicoleli11 — COMMENTED** [review]
maybe set a value first
value={value} cant read

**Review by nicoleli11 — APPROVED** [review]

**Review by dddora — APPROVED** [review]
Good job!!!

**Pull request merged**
